### ISSUE TITLE
Quiz is broken

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/looping-quiz#2] opened 2015-11-01 19:48 UTC
Not rendering as quiz, also not showing quiz light in right rail

@SophieDeBenedetto @ktravers please take a look at markdown

**Comment by SophieDeBenedetto** [comment] 2015-11-01 19:51
@matbalez  I'm in car on my way to visit family. Should be back online in the next two hours and I'll take a look then.

**Comment by matbalez-zz** [comment] 2015-11-01 19:56
Thank you! For what it's worth--not urgent, can be fixed in AM.

**Comment by SophieDeBenedetto** [comment] 2015-11-01 20:05
@matbalez where can I see this deployed/what track?

**Comment by matbalez-zz** [comment] 2015-11-01 20:18
It is in the Full Stack Web Development track (deployed to batch v-000)

**Comment by SophieDeBenedetto** [comment] 2015-11-01 20:23
hi @ktravers, i fixed the markdown and i think it's valid now (def take a second look, i know it's super finnicky). Quiz appears like a quiz in Learn now but you can't select any answers.

**Comment by ktravers** [comment] 2015-11-01 21:28
Will be home shortly & will take a look.

On Sunday, November 1, 2015, Sophie DeBenedetto notifications@github.com
wrote:

> hi @ktravers https://github.com/ktravers, i fixed the markdown and i
> think it's valid now (def take a second look, i know it's super finnicky).
> Quiz appears like a quiz in Learn now but you can't select any answers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/learn-co-curriculum/looping-quiz/issues/2#issuecomment-152860625
> .

## 

best,
Kate

Kate Travers
646.402.4500  |  travers.kt@gmail.com  |  www.kate-travers.com

**Comment by ktravers** [comment] 2015-11-02 01:19
just added myself to the v-000 batch and tested out the quiz on production. it's working as intended for me. @SophieDeBenedetto what steps should i follow to see this thing in it's broken state? normally when you can't select answers, it's a) a javascript error or b) quiz is missing an assessment, but not seeing anything like that on my end.

this might also be related to open issue [#4793](https://github.com/flatiron-labs/ironboard/issues/4793).

oh also, the markdown looks perfect. But this repo needs `.learn`, `CONTRIBUTING.md`, and `LICENSE.md` files, right?

**Comment by SophieDeBenedetto** [comment] 2015-11-02 02:51
@ktravers  yep it does need .learn, contributing etc, i will add now. 

broken quiz is happening here: https://learn.co/admin/lessons/12856

but maybe you or someone else told me it shouldnt work there anyway? not really remembering clearly.

**Comment by ktravers** [comment] 2015-11-04 18:06
pushed the fix for this yesterday afternoon [[#4991](https://github.com/flatiron-labs/ironboard/pull/4991)]. just checked on Full Stack Web Development track, and looks like quiz is working as intended now. 

does someone else want to confirm before closing this issue?

**Closed as completed** 2015-11-23 18:35 UTC
